// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      throw UnsupportedError(
        'DefaultFirebaseOptions have not been configured for web - '
        'you can reconfigure this by running the FlutterFire CLI again.',
      );
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for macos - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyDf_16XFTnOza08i3ro0gsA5i90UCjEIRs',
    appId: '1:678672927365:android:18d3069da8f3b07de237ec',
    messagingSenderId: '678672927365',
    projectId: 'bank-app-3f916',
    databaseURL: 'https://bank-app-3f916-default-rtdb.firebaseio.com',
    storageBucket: 'bank-app-3f916.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyDA5hcuOfjBREzJhtd35XoeZQGquNitKZo',
    appId: '1:678672927365:ios:4f65d9d36e6d7608e237ec',
    messagingSenderId: '678672927365',
    projectId: 'bank-app-3f916',
    databaseURL: 'https://bank-app-3f916-default-rtdb.firebaseio.com',
    storageBucket: 'bank-app-3f916.appspot.com',
    iosClientId: '678672927365-hub3bvuqrstf6luu0p7gsjbcl3kv0rne.apps.googleusercontent.com',
    iosBundleId: 'najot.bank.uz.bank',
  );
}
